service: quiztopia

provider:
  name: aws
  runtime: nodejs22.x
  region: eu-north-1

  environment:
    QUIZGAME_TABLE: ${env:QUIZGAME_TABLE}
    JWT_SECRET: ${env:JWT_SECRET}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource:
      -  arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.QUIZGAME_TABLE}

functions: 
  signup:
    handler: functions/signUp/index.handler
    events:
      - http:
          path: signup
          method: post

  login:
    handler:  functions/logIn/index.handler
    events:
      - http:
          path: login
          method: post
  
  createQuiz:
    handler: functions/createQuiz/index.handler
    events:
      - http:
          path: quiz
          method: post

  deleteQuiz:
    handler: functions/deleteQuiz/index.handler
    events:
      - http:
          path: quiz/{quizId}
          method: delete

  getQuizByQuizId:
    handler: functions/getQuizByQuizId/index.handler
    events:
      - http:
          path: quiz/{quizId}
          method: get
          
  getAllQuizzesByUser:
    handler: functions/getAllQuizzesByUser/index.handler
    events:
      - http:
          path: quizzes/user/{userId}
          method: get

  getAllQuizzesByCoordinates:
    handler: functions/getAllQuizzesByCoordinates/index.handler
    events:
      - http:
          path: quizzes/location
          method: get
          request:
            parameters:
              querystrings:
                latitude: true
                longitude: true


  addQuestion:
    handler: functions/addQuestionToQuiz/index.handler
    events:
      - http:
          path: quiz/{quizId}/question
          method: post

  updateQuestion:
    handler: functions/updateQuestion/index.handler
    events:
      - http:
          path: quiz/{quizId}/question/{questionId}
          method: put

  deleteQuestion:
    handler: functions/deleteQuestion/index.handler
    events:
      - http:
          path: quiz/{quizId}/question/{questionId}
          method: delete

  answerQuestion:
    handler: functions/answerQuestion/index.handler
    events:
      - http:
          path: quiz/{quizId}/question/{questionId}/answer
          method: post

 